FROM wazoplatform/wazo-purge-db

RUN pip install sqlalchemy_utils==0.38.2

COPY . /usr/src/wazo-call-logd
WORKDIR /usr/src/wazo-call-logd

ENV PYTHONDONTWRITEBYTECODE='true'

RUN python3 -m pip install -e .

ENTRYPOINT ["./integration_tests/docker/entrypoint.sh"]
